language: node_js
node_js:
  - '16'
cache:
  npm: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
jobs:
  include:
    - name: 'Test'
      script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc && cat ~/.npmrc
env:
  global:
    - NODE_OPTIONS="--max-old-space-size=8192"
