module.exports = {
  'American Express': 'americanexpress',
  'Arkéa Banque Privée': 'arkea',
  'AXA Banque': 'axabanque102',
  'Floa Bank': 'banquecasino',
  'Banque Populaire': 'banquepopulaire',
  Milleis: 'barclays136',
  BforBank: 'bforbank97',
  'BNP Paribas': 'bnpparibas82',
  Bolden: 'bolden',
  Boursorama: 'boursorama83',
  BRED: 'bred',
  "Caisse d'Épargne Particuliers": 'caissedepargne1',
  'Carrefour Banque': 'carrefour159',
  Cetelem: 'cetelem',
  CIC: 'cic63',
  'Compte Nickel': 'comptenickel168',
  'Crédit Agricole': 'caatlantica3',
  'Crédit Coopératif': 'creditcooperatif148',
  'Crédit du Nord': 'cdngroup88',
  'Crédit Maritime': 'creditmaritime',
  'Crédit Mutuel': 'cic45',
  'Crédit Mutuel de Bretagne': 'cic45',
  'Crédit Mutuel du Sud Ouest': 'cic45',
  Fortuneo: 'fortuneo84',
  'Hello bank!': 'hellobank145',
  'HSBC Continental Europe': 'hsbc119',
  'ING France': 'ingdirect95',
  'La Banque Postale': 'labanquepostale44',
  LCL: 'lcl-linxo',
  'MAIF Vie': 'maifviebank',
  Monabanq: 'monabanq96',
  'Société Marseillaise de Crédit': 'cdngroup109',
  'Société Générale': 'societegenerale',
  'Connecteur de test': 'bankingconnectortest',
  Revolut: 'revolut',
  N26: 'n26',
  Sofinco: 'sofinco',
  Oney: 'oney',
  'Banque BCP': 'bcp',
  'Banque Courtois': 'courtois',
  'Banque Kolb': 'kolb',
  'Banque Laydernier': 'laydernier',
  'Banque Rhône-Alpes': 'rhonealpes',
  'Banque Tarneaud': 'tarneaud',
  'Banque Transatlantique': 'transatlantique',
  'Gan Assurances': 'gan',
  Groupama: 'groupama',
  'MAAF Vie': 'maafvie',
  'Moneo Resto': 'moneoresto',
  PayPal: 'paypal',
  Yomoni: 'yomoni',
  WeSave: 'wesave',
  'Orange Bank': 'orangebank',
  'MAIF Socram Banque': 'socram',
  'Socram Banque': 'socramcredit',
  'Macif Espace Banque': 'socrammacif',
  'Natixis Interépargne': 'natixis',
  Amundi: 'amundiee',
  'Banque Européenne Crédit Mutuel': 'becm',
  Afer: 'afer',
  'CIC Épargne Salariale': 'cicee',
  'PSA Banque': 'psa',
  'Crédit Agricole - Epargne Longue des Salariés': 'caels',
  LinXea: 'linxea',
  'BPE Banque privée': 'bpe',
  Palatine: 'palatine',
  'Crédit Mutuel Épargne Salariale': 'creditmutueles',
  'Renault Bank': 'zesto',
  'assurancevie.com': 'assuranceviecom',
  'mes-placements.fr': 'mesplacementsfr',
  'Banque SBE': 'sbe',
  Sharinbox: 'sharinbox',
  'Société Générale Épargne Salariale': 'esalia',
  'Epsens Épargne Salariale': 'epsenses',
  'Crédit Foncier': 'creditfoncier',
  'Banque Française Commerciale Océan Indien': 'bfcoi',
  MACSF: 'macsf',
  'Banque Nuger': 'nuger',
  'Banque Chalus': 'chalus',
  Epargnissimo: 'epargnissimo',
  'AXA Épargne Salariale': 'axaes',
  Sogeretraite: 'sogeretraite',
  'Banque Edmond de Rothschild': 'edmondderothschild',
  Mutavie: 'mutavie',
  Agipi: 'agipi',
  CACEIS: 'ccso',
  'Allianz Retraite Collective': 'allianzretraitecollective',
  'Banque Transatlantique épargne salariale': 'transatlantiquees',
  'Ageas ': 'ageas',
  Manymore: 'manymore',
  Altaprofits: 'altaprofits',
  'AXA Épargne Retraite': 'axaer',
  'Banque Postale Épargne Salariale': 'banquepostaleee',
  'BNP Paribas Épargne Salariale': 'bnpes',
  'Crédit du Nord Épargne Salariale': 'creditdunordes',
  Generali: 'generali',
  'Groupama Épargne Salariale': 'groupamaes',
  'Oddo - Banque Privée': 'oddo',
  Spirica: 'spirica',
  SwissLife: 'swisslife',
  'SwissLife Banque Privée': 'swisslifebp',
  'Union Financière de France': 'unionfinancieredefrance',
  Nalo: 'nalo'
}
