module.exports = {
  'AXA Banque': 'axabanque102',
  '/Banque Populaire.*/': 'banquepopulaire',
  BforBank: 'bforbank97',
  'BNP Paribas': 'bnpparibas82',
  BNPP: 'bnpparibas82',
  '/Boursorama.*/': 'boursorama83',
  casden: 'casden173',
  '/Hello bank!.*/': 'hellobank145',
  Bred: 'bred',
  CA: 'caatlantica3',
  'Carrefour Banque': 'carrefour159',
  "/Caisse d'Épargne.*/": 'caissedepargne1',
  'Compte Nickel': 'comptenickel168',
  '/^CIC.*/': 'cic63',
  'Crédit Agricole': 'caatlantica3',
  'Crédit Coopératif': 'creditcooperatif148',
  '/Crédit du Nord.*/': 'cdngroup88',
  '/Crédit Maritime.*/': 'creditmaritime',
  '/Crédit Mutuel.*/': 'cic45',
  Fortuneo: 'fortuneo84',
  'Hello bank!': 'hellobank145',
  'HSBC France': 'hsbc119',
  HSBC: 'hsbc119',
  '/^ING.*/': 'ingdirect95',
  '/La Banque Postale.*/': 'labanquepostale44',
  '/LCL.*/': 'lcl-linxo',
  Milleis: 'barclays136',
  Monabanq: 'monabanq96',
  'Société Générale': 'societegenerale',
  'Société marseillaise de crédit': 'cdngroup109'
}
