
import AppLinker from "cozy-ui/transpiled/react/AppLinker"
import AppSections from "cozy-ui/transpiled/react/AppSections"
import AppTile from "cozy-ui/transpiled/react/AppTile"
import CipherIcon from "cozy-ui/transpiled/react/CipherIcon"
import ContactPicker from "cozy-ui/transpiled/react/ContactPicker"
import AddModal from "cozy-ui/transpiled/react/Contacts/AddModal"
import GroupsSelect from "cozy-ui/transpiled/react/Contacts/GroupsSelect"
import Header from "cozy-ui/transpiled/react/Contacts/Header"
import ContactsList from "cozy-ui/transpiled/react/ContactsList"
import ContactsListModal from "cozy-ui/transpiled/react/ContactsListModal"
import Field from "cozy-ui/transpiled/react/Field"
import FileImageLoader from "cozy-ui/transpiled/react/FileImageLoader"
import FileImageFilePickerLoader from "cozy-ui/transpiled/react/FilePicker"
import { useClientErrors } from "cozy-ui/transpiled/react/hooks/useClientErrors"
import ListItemByDoc from "cozy-ui/transpiled/react/ListItem/ListItemByDoc"
import ListItemBase from "cozy-ui/transpiled/react/ListItem/ListItemBase"
import ListItemContact from "cozy-ui/transpiled/react/ListItem/ListItemContact"
import ListItemFile from "cozy-ui/transpiled/react/ListItem/ListItemFile"
import Paywall from "cozy-ui/transpiled/react/Paywall"
import CozyTheme, { useCozyTheme } from "cozy-ui/transpiled/react/providers/CozyTheme"
import Intent from "cozy-ui/transpiled/react/providers/Intent"
import ShortcutTile from "cozy-ui/transpiled/react/ShortcutTile"
import SquareAppIcon from "cozy-ui/transpiled/react/SquareAppIcon"
import Storage from "cozy-ui/transpiled/react/Storage"
import UploadQueue from "cozy-ui/transpiled/react/UploadQueue"
import Wizard from "cozy-ui/transpiled/react/Wizard"

// modified with path modification
import AuthentificationDialog from "cozy-ui/transpiled/react/CozyDialogs/SpecificDialogs/AuthentificationDialog"
import CollectionField from "cozy-ui/transpiled/react/Labs/CollectionField"
import IntentDialogOpener from "cozy-ui/transpiled/react/IntentDialogOpener"
import IntentIframe from "cozy-ui/transpiled/react/IntentIframe"
import QualificationGrid from "cozy-ui/transpiled/react/QualificationGrid"
import QualificationIcon from "cozy-ui/transpiled/react/QualificationIcon"
import QualificationItem from "cozy-ui/transpiled/react/QualificationItem"
import QualificationModal from "cozy-ui/transpiled/react/QualificationModal"
import QuotaAlert from "cozy-ui/transpiled/react/deprecated/QuotaAlert"
