import AppLinker from "cozy-ui-plus/dist/AppLinker"
import AppSections from "cozy-ui-plus/dist/AppSections"
import AppTile from "cozy-ui-plus/dist/AppTile"
import CipherIcon from "cozy-ui-plus/dist/CipherIcon"
import ContactPicker from "cozy-ui-plus/dist/ContactPicker"
import AddModal from "cozy-ui-plus/dist/Contacts/AddModal"
import GroupsSelect from "cozy-ui-plus/dist/Contacts/GroupsSelect"
import Header from "cozy-ui-plus/dist/Contacts/Header"
import ContactsList from "cozy-ui-plus/dist/ContactsList"
import ContactsListModal from "cozy-ui-plus/dist/ContactsListModal"
import Field from "cozy-ui-plus/dist/Field"
import FileImageLoader from "cozy-ui-plus/dist/FileImageLoader"
import FileImageFilePickerLoader from "cozy-ui-plus/dist/FilePicker"
import { useClientErrors } from "cozy-ui-plus/dist/hooks/useClientErrors"
import ListItemByDoc from "cozy-ui-plus/dist/ListItem/ListItemByDoc"
import ListItemBase from "cozy-ui-plus/dist/ListItem/ListItemBase"
import ListItemContact from "cozy-ui-plus/dist/ListItem/ListItemContact"
import ListItemFile from "cozy-ui-plus/dist/ListItem/ListItemFile"
import Paywall from "cozy-ui-plus/dist/Paywall"
import CozyTheme, { useCozyTheme } from "cozy-ui-plus/dist/providers/CozyTheme"
import Intent from "cozy-ui-plus/dist/providers/Intent"
import ShortcutTile from "cozy-ui-plus/dist/ShortcutTile"
import SquareAppIcon from "cozy-ui-plus/dist/SquareAppIcon"
import Storage from "cozy-ui-plus/dist/Storage"
import UploadQueue from "cozy-ui-plus/dist/UploadQueue"
import Wizard from "cozy-ui-plus/dist/Wizard"

// modified with path modification
import AuthentificationDialog from "cozy-ui-plus/dist/Dialogs/AuthentificationDialog"
import CollectionField from "cozy-ui-plus/dist/CollectionField"
import IntentDialogOpener from "cozy-ui-plus/dist/Intent/IntentDialogOpener"
import IntentIframe from "cozy-ui-plus/dist/Intent/IntentIframe"
import QualificationGrid from "cozy-ui-plus/dist/Qualification/QualificationGrid"
import QualificationIcon from "cozy-ui-plus/dist/Qualification/QualificationIcon"
import QualificationItem from "cozy-ui-plus/dist/Qualification/QualificationItem"
import QualificationModal from "cozy-ui-plus/dist/Qualification/QualificationModal"
import QuotaAlert from "cozy-ui-plus/dist/Paywall/QuotaPaywall"
