name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: |
          yarn lint
          yarn lint:md -f
      - name: Test
        run: yarn test
      - name: Check documentation
        run: |
          git diff --exit-code -- '*.md' || (echo "Docs are not up-to-date, please run yarn lint:md -f and repush" && exit 1)
      - name: Git Identity
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/$GITHUB_REPOSITORY
      - name: NPM Identity
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - name: Publish to NPM
        if: github.ref == 'refs/heads/master'
        run: yarn lerna publish --yes -m "[skip ci] Publish"
